In [5]:
import pandas as pd
import numpy as np

path = "DB-Output_original.csv"
data = pd.read_csv(path)

data = data.loc[:, :'Moves']
data.head()

,Instance's Name,Initial Solution,OFIS,Moves
0,c101_21_25.txt,"[['D0', 'C21', 'C26', 'D0'], ['D0', 'C65', 'C6...",30978.64707,"['null', 'null', 'DemandBasedDestroyCustomer',..."
1,c101_21_25.txt,"[['D0', 'C21', 'C26', 'D0'], ['D0', 'C65', 'C6...",30978.64707,"['null', 'null', 'ShawDestroyCustomer', 'Greed..."
2,c101_21_25.txt,"[['D0', 'C21', 'C26', 'D0'], ['D0', 'C65', 'C6...",30978.64707,"['null', 'null', 'WorstTimeDestroyCustomer', '..."
3,c101_21_25.txt,"[['D0', 'C21', 'C26', 'D0'], ['D0', 'C65', 'C6...",30978.64707,"['null', 'null', 'GreedyRouteRemoval', 'Greedy..."
4,c101_21_25.txt,"[['D0', 'C21', 'C26', 'D0'], ['D0', 'C65', 'C6...",30978.64707,"['RandomDestroyStation', 'ProbabilisticBestRep..."

In [6]:
init_sol = data['Initial Solution']
print("Type of 'init_sol':", type(init_sol))

init_sol[0]
print("Type of 'init_sol[0]':", type(init_sol[0]))

init_sol.head()

Type of 'init_sol': <class 'pandas.core.series.Series'>
Type of 'init_sol[0]': <class 'str'>

0    [['D0', 'C21', 'C26', 'D0'], ['D0', 'C65', 'C6...
1    [['D0', 'C21', 'C26', 'D0'], ['D0', 'C65', 'C6...
2    [['D0', 'C21', 'C26', 'D0'], ['D0', 'C65', 'C6...
3    [['D0', 'C21', 'C26', 'D0'], ['D0', 'C65', 'C6...
4    [['D0', 'C21', 'C26', 'D0'], ['D0', 'C65', 'C6...
Name: Initial Solution, dtype: object

Somma delle occorrenza di uno specifico luogo all'interno di tutto il DataFrame, nella colonna "Initial Solution"

In [7]:
print("D0 total: ", init_sol.str.count('D0').sum())
print("C21 total: ", init_sol.str.count('C21').sum())
print("C87 total: ", init_sol.str.count('C87').sum())
print("C27 total: ", init_sol.str.count('C27').sum())

D0 total:  1817188
C21 total:  24067
C87 total:  18864
C27 total:  24666

# Pulizia dei dati

Si prende la colonna contenente i luoghi "Initial Solution" (che è una serie di pandas) e tramite la funzione str.replace() si pulisce la stringa, rimuovendo la punteggiatura speciale (parentesi quadre, virgole e apici) con un carattere null.

Si stampa poi la colonna "Initial Solution" ripulita.

In [8]:
data["Initial Solution"] = data["Initial Solution"].str.replace("[","")
data["Initial Solution"] = data["Initial Solution"].str.replace("]","")
data["Initial Solution"] = data["Initial Solution"].str.replace(",","")
data["Initial Solution"] = data["Initial Solution"].str.replace("'","")

data["Initial Solution"].head()

/var/folders/_t/_x_rzsrx5vd2_mn90dgnz43h0000gn/T/ipykernel_2816/3585595387.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data["Initial Solution"] = data["Initial Solution"].str.replace("[","")
/var/folders/_t/_x_rzsrx5vd2_mn90dgnz43h0000gn/T/ipykernel_2816/3585595387.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data["Initial Solution"] = data["Initial Solution"].str.replace("]","")

0    D0 C21 C26 D0 D0 C65 C61 D0 D0 C24 C50 D0 D0 C...
1    D0 C21 C26 D0 D0 C65 C61 D0 D0 C24 C50 D0 D0 C...
2    D0 C21 C26 D0 D0 C65 C61 D0 D0 C24 C50 D0 D0 C...
3    D0 C21 C26 D0 D0 C65 C61 D0 D0 C24 C50 D0 D0 C...
4    D0 C21 C26 D0 D0 C65 C61 D0 D0 C24 C50 D0 D0 C...
Name: Initial Solution, dtype: object

# Divisione dei luoghi

Si "isola" la singola colonna "Initial Solution" inserendola nella variabile "init_sol", che diventa una serie a sua volta.

In [9]:
init_sol = data["Initial Solution"]
print(init_sol)
type(init_sol)

0        D0 C21 C26 D0 D0 C65 C61 D0 D0 C24 C50 D0 D0 C...
1        D0 C21 C26 D0 D0 C65 C61 D0 D0 C24 C50 D0 D0 C...
2        D0 C21 C26 D0 D0 C65 C61 D0 D0 C24 C50 D0 D0 C...
3        D0 C21 C26 D0 D0 C65 C61 D0 D0 C24 C50 D0 D0 C...
4        D0 C21 C26 D0 D0 C65 C61 D0 D0 C24 C50 D0 D0 C...
                               ...
35406    D0 C5 C2 C1 C14 C25 C21 D0 D0 C89 C84 C83 C77 ...
35407    D0 C5 C2 C1 C14 C25 C21 D0 D0 C89 C84 C83 C77 ...
35408    D0 C5 C2 C1 C14 C25 C21 D0 D0 C89 C84 C83 C77 ...
35409    D0 C5 C2 C1 C14 C25 C21 D0 D0 C89 C84 C83 C77 ...
35410    D0 C5 C2 C1 C14 C25 C21 D0 D0 C89 C84 C83 C77 ...
Name: Initial Solution, Length: 35411, dtype: object

pandas.core.series.Series

La singola riga della serie equivale ad una stringa. Ad esempio "init_sol[0]" equivale ad una stringa contenente "D0 C21 C26 D0 D0 C65 C61 D0 D0 C24 C50 D0 ..."

Attraverso il metodo split(), inserito in un ciclo for che itera ogni riga di "init_sol", si splitta la stringa in considerazione rispetto al carattere spazio e la si inserisce tramite .append() nella lista "places" inizialmente vuota. Ogni volta che il metodo split() trova uno spazio, viene rilevato un elemento (luogo).

La stringa splittata per singolo elemento viene inserita in una lista chiamata "places", dove sono presenti ancora ripetizioni.

Applicando il cast di tipo da lista a set, e di nuovo da set a lista, si ha in output una lista senza ripetizioni chiamata "distinct_places".
Successivamente, attraverso il metodo .sort(), la lista viene ordinata in modo alfabetico.

In [10]:
places = []
for row in init_sol:
    for elem in row.split():
        places.append(elem)

distinct_places = list(set(places))

distinct_places.sort()
print("\nLa lista di tutti i diversi luoghi (ordinati) è:\n", distinct_places)

print("\nLa lista contiene", len(distinct_places), "diversi luoghi")
print("\nPrint di diversi luoghi:\n", distinct_places[0], distinct_places[5], distinct_places[23])

La lista di tutti i diversi luoghi (ordinati) è:
 ['C1', 'C10', 'C100', 'C11', 'C12', 'C13', 'C14', 'C15', 'C16', 'C17', 'C18', 'C19', 'C2', 'C20', 'C21', 'C22', 'C23', 'C24', 'C25', 'C26', 'C27', 'C28', 'C29', 'C3', 'C30', 'C31', 'C32', 'C33', 'C34', 'C35', 'C36', 'C37', 'C38', 'C39', 'C4', 'C40', 'C41', 'C42', 'C43', 'C44', 'C45', 'C46', 'C47', 'C48', 'C49', 'C5', 'C50', 'C51', 'C52', 'C53', 'C54', 'C55', 'C56', 'C57', 'C58', 'C59', 'C6', 'C60', 'C61', 'C62', 'C63', 'C64', 'C65', 'C66', 'C67', 'C68', 'C69', 'C7', 'C70', 'C71', 'C72', 'C73', 'C74', 'C75', 'C76', 'C77', 'C78', 'C79', 'C8', 'C80', 'C81', 'C82', 'C83', 'C84', 'C85', 'C86', 'C87', 'C88', 'C89', 'C9', 'C90', 'C91', 'C92', 'C93', 'C94', 'C95', 'C96', 'C97', 'C98', 'C99', 'D0', 'S0', 'S1', 'S10', 'S11', 'S12', 'S13', 'S14', 'S15', 'S16', 'S17', 'S18', 'S19', 'S2', 'S20', 'S3', 'S4', 'S5', 'S7', 'S9']

La lista contiene 120 diversi luoghi

Print di diversi luoghi:
 C1 C13 C3

# Creazione della matrice 

Si procede quindi alla creazione della matrice che ha come dimensioni la lunghezza della lista "distinct_places", ovvero il numero dei diversi luoghi presenti nel dataframe iniziale

In [13]:
print("\nLa lista 'distinct_places' contiene", len(distinct_places), "diversi luoghi\n")
a = len(distinct_places)

dataframe = pd.DataFrame(0, index=distinct_places, columns=distinct_places)
dataframe.head()

La lista 'distinct_places' contiene 120 diversi luoghi

,C1,C10,C100,C11,C12,C13,C14,C15,C16,C17,...,S17,S18,S19,S2,S20,S3,S4,S5,S7,S9
C1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C100,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
places_matrix = np.zeros((a, a))
print("Matrice dei vari luoghi di dimensione", places_matrix.shape, ":\n", places_matrix)